### ISSUE TITLE
Bug in recursiveSizeNF

### ISSUE THREAD

**Issue by noughtmare** [def-/ghc-datasize#12]
Running `recursiveSizeNF` gives me unexpected results:

```haskell
ghci> recursiveSizeNF [1..1000 :: Int]
600
ghci> recursiveSizeNF [1..10000 :: Int]
600
```

Using `$!!` does seem to give the correct numbers:

```haskell
ghci> recursiveSize $!! [1..1000 :: Int]
40016
ghci> recursiveSize $!! [1..10000 :: Int]
400016
```

Maybe `recursiveSizeNF` should just be defined as follows:

```haskell
recursiveSizeNF x = recursiveSize $!! x
```

**Comment by def-** [comment]
I don't think this is unexpected. recursiveSizeNF just calls DeepSeq.force, as documented.

**Comment by noughtmare** [comment]
Maybe the "to force it into Normal Form" should be removed from the documentation then?
