### ISSUE TITLE
Add NFData constraint to the data structure we're measuing?

### ISSUE THREAD

**Issue by erikd** [def-/ghc-datasize#3]
While trying to come up with a half way reasonable timing test for the changes in my other PR I ran into a GHC bug which I've raised here: https://ghc.haskell.org/trac/ghc/ticket/12492 . Interestingly, the problem disappears if I do a `deepseq` on the data structure before calling `recursiveSize`

I wonder if its worth modifying `recursiveSize` so the signature is:

```
recursiveSize :: NFData a => a -> IO Word
```

or, alternatively, adding a `recursiveSizeNF` with the above type signature that calls `Control.Deepseq.force` on the structure before calling the existing `recursiveSize`.

Happy to implement and test this and then add it to my existing PR if you can tell me which of the above two solutions you prefer.

**Comment by def-** [comment]
Well, actually ghc-datasize is _not_ just a Haskell program calling public API, it used ghc-heap-view to get deep into GHC's internals and thus can cause all kinds of problems that would never happen in regular Haskell code.

I think the user guide explains evaluating data structures reasonably well: http://felsin9.de/nnis/ghc-datasize/

**Comment by erikd** [comment]
> Well, actually ghc-datasize is not just a Haskell program calling public API

By that I meant it is some horrible C hack and then I looked at the ghc-heap-view internals which does indeed have code in C and Cminusminus.

However, regardless of that I would still find 

```
recursiveSizeNF :: NFData a => a -> IO Word
```

useful. In fact I am already using it two places and would be happy to see to move into ghc-datasize itself.

**Update:** Fix typo. `NFData a` is a typeclass constraint, not a function parameter. That may have caused some confusion.

**Comment by def-** [comment]
I don't understand why `recursiveSizeNF foo` is better than `recursiveSize $!! foo`

**Comment by erikd** [comment]
The difference is convenience.

**Comment by def-** [comment]
It's 1 letter more, I don't really see it.Then you'd need to add an `NF` variant of every function?

**Comment by erikd** [comment]
> Then you'd need to add an NF variant of every function?

Sorry, why? The implementation is:

```
recursiveSizeNF :: NFData a => a -> IO Word
recursiveSizeNF = recursiveSize . force
```

That acts like a compiler checked precondition for using the function. It ensures that the data structure and all its components have `NFData` typeclass instances and does a `force` all in one go. I'm currently using this function _instead_ of `recursiveSize` for exactly this reason.

The problem with `recursiveSize $!! foo` is that if someone other than the original coder changes the `foo` data structure so that some component doesn't have an `NFData` instance, they may naively switch from `$!!` to `$!` and suddenly no longer get the results expected by the original coder.

With `recursiveSizeNF` they would either realize that their additions to the data structure requires `NFData` instances, or search for alternatives to `recursiveSizeNF` at which point they are likely to read the documentation and figure out that switching to `recusiveSize` would be a bad idea.

**Comment by def-** [comment]
But in the same way another coder can change it to call `recursiveSize` instead of `recursiveSizeNF` when it stops compiling. Anyway, I don't mind adding it much, I just don't believe it adds much useful. So go ahead with the PR if you want to.

**Comment by erikd** [comment]
PR #4.
