### ISSUE TITLE
Incorrect size of String

### ISSUE THREAD

**Issue by chshersh** [def-/ghc-datasize#8]
I'm trying to calculate the size of `String` in Haskell using `ghc-datasize` but the `recursiveSize` function returns `88` in GHCi` for strings of different lengths:

```haskell
λ: recursiveSize $! ("a" :: String)
88
λ: recursiveSize $! ("aa" :: String)
88
λ: recursiveSize $! ("aaa" :: String)
88
λ: recursiveSize $! ("abc" :: String)
88
```

Do I calculate the size in the wrong way?

**Comment by def-** [comment]
Strings are composite data structures, so you'll need to use $!! as described in the user guide: http://felsin9.de/nnis/ghc-datasize/

    λ> recursiveSize $!! "foobar"
    248

**Comment by chshersh** [comment]
@def- Thanks, that works! It's hard for me to understand now why it's needed and how everything is working... But now I'm able to play with it and calculate sizes of various structures. This is very nice!

**Comment by def-** [comment]
It becomes more clear once you look at it with ghc-heap-view. It's basically just implementation details of GHC about how much of the string is yet evaluated etc.
